### ISSUE TITLE
InvalidPathException

### ISSUE THREAD

**Issue by clankill3r** [padreati/rapaio-jupyter-kernel#46]
During the installer I got a invalid path exception.
I copied the jar file manually and it works now so I'm happy :)

```
kernel.json:
{
  "argv": [
    "java",
    "--enable-preview",
    "--add-modules",
    "java.base,jdk.incubator.vector",
    "-jar",
    "C:\\Users\\clank\\AppData\\Roaming/jupyter/kernels/rapaio-jupyter-kernel/rapaio-jupyter-kernel-1.3.0.jar",
    "{connection_file}"
  ],
  "display_name": "Java (Rapaio Jupyter)",
  "language": "java",
  "interrupt_mode": "message",
  "env": {
    "RJK_COMPILER_OPTIONS": "",
    "RJK_INIT_SCRIPT": "",
    "RJK_TIMEOUT_MILLIS": "5000"
  }
}
Installer is ready. Do you want to continue [Y/N] ?
Y
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/clank/Downloads/rapaio-jupyter-kernel-1.3.0.jar
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
        at java.base/java.nio.file.Path.of(Path.java:148)
        at org.rapaio.jupyter.kernel.install.Installer.copyJarFile(Installer.java:176)
        at org.rapaio.jupyter.kernel.install.Installer.install(Installer.java:162)
        at org.rapaio.jupyter.kernel.MainApp.main(MainApp.java:35)

```

**Comment by padreati** [comment]
I don't have a windows host for testing. I will add a virtual box for that purpose and investigate the issue. Thank you, I will look into it.

**Comment by padreati** [comment]
I found where the error is. I work on producing an unit test to fix that.

**Comment by clankill3r** [comment]
Ok, let me know if I can help

**Comment by padreati** [comment]
It seems that it was fixed now.
